services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - db_data_volume:/var/lib/postgresql/data
    networks:
      - internal_network

  api:
    build:
      context: database/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - internal_network
    platform: linux/amd64

  frontend:
    build:
      context: client/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - internal_network

  nginx-proxy:
    image: nginx:alpine
    restart: always
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    networks:
      - internal_network
    ports:
      - 3005:80

volumes:
  db_data_volume:

networks:
  internal_network:
    driver: bridge
