"""
This type stub file was generated by pyright.
"""

import sys

SOCKET_ERROR = ConnectionError
if sys.platform.startswith('win'):
    def rename_file(current_filename, new_filename): # -> None:
        ...
    
else:
    rename_file = ...
def filter_python_deprecation_warnings(): # -> None:
    """
    Invoking this filter acknowledges your runtime will soon be deprecated
    at which time you will stop receiving all updates to your client.
    """
    ...

