"""
This type stub file was generated by pyright.
"""

"""
NOTE: All functions in this module are considered private and are
subject to abrupt breaking changes. Please do not use them directly.

"""
logger = ...
def maybe_compress_request(config, request_dict, operation_model): # -> None:
    """Attempt to compress the request body using the modeled encodings."""
    ...

COMPRESSION_MAPPING = ...
