"""
This type stub file was generated by pyright.
"""

HISTORY_RECORDER = ...
logger = ...
class BaseHistoryHandler:
    def emit(self, event_type, payload, source):
        ...
    


class HistoryRecorder:
    def __init__(self) -> None:
        ...
    
    def enable(self): # -> None:
        ...
    
    def disable(self): # -> None:
        ...
    
    def add_handler(self, handler): # -> None:
        ...
    
    def record(self, event_type, payload, source=...): # -> None:
        ...
    


def get_global_history_recorder(): # -> HistoryRecorder:
    ...

