"""
This type stub file was generated by pyright.
"""

class ClientDocumenter:
    _CLIENT_METHODS_FILTERS = ...
    def __init__(self, client, root_docs_path, shared_examples=...) -> None:
        ...
    
    def document_client(self, section): # -> None:
        """Documents a client and its methods

        :param section: The section to write to.
        """
        ...
    


class ClientExceptionsDocumenter:
    _USER_GUIDE_LINK = ...
    _GENERIC_ERROR_SHAPE = ...
    def __init__(self, client, root_docs_path) -> None:
        ...
    
    def document_exceptions(self, section): # -> None:
        ...
    


class ClientContextParamsDocumenter:
    _CONFIG_GUIDE_LINK = ...
    OMITTED_CONTEXT_PARAMS = ...
    def __init__(self, service_name, context_params) -> None:
        ...
    
    def document_context_params(self, section): # -> None:
        ...
    


