"""
This type stub file was generated by pyright.
"""

class PaginatorDocumenter:
    def __init__(self, client, service_paginator_model, root_docs_path) -> None:
        ...
    
    def document_paginators(self, section): # -> None:
        """Documents the various paginators for a service

        param section: The section to write to.
        """
        ...
    


def document_paginate_method(section, paginator_name, event_emitter, service_model, paginator_config, include_signature=...): # -> None:
    """Documents the paginate method of a paginator

    :param section: The section to write to

    :param paginator_name: The name of the paginator. It is snake cased.

    :param event_emitter: The event emitter to use to emit events

    :param service_model: The service model

    :param paginator_config: The paginator config associated to a particular
        paginator.

    :param include_signature: Whether or not to include the signature.
        It is useful for generating docstrings.
    """
    ...

