"""
This type stub file was generated by pyright.
"""

class ServiceDocumenter:
    def __init__(self, service_name, session, root_docs_path) -> None:
        ...
    
    def document_service(self): # -> bytes:
        """Documents an entire service.

        :returns: The reStructured text of the documented service.
        """
        ...
    
    def title(self, section): # -> None:
        ...
    
    def table_of_contents(self, section): # -> None:
        ...
    
    def client_api(self, section): # -> None:
        ...
    
    def client_exceptions(self, section): # -> None:
        ...
    
    def paginator_api(self, section): # -> None:
        ...
    
    def waiter_api(self, section): # -> None:
        ...
    
    def get_examples(self, service_name, api_version=...):
        ...
    
    def client_context_params(self, section): # -> None:
        ...
    


