"""
This type stub file was generated by pyright.
"""

"""Binary input/output support routines."""
def i8(c):
    ...

def o8(i): # -> bytes:
    ...

def i16le(c, o=...): # -> Any:
    """
    Converts a 2-bytes (16 bits) string to an unsigned integer.

    :param c: string containing bytes to convert
    :param o: offset of bytes to convert in string
    """
    ...

def si16le(c, o=...): # -> Any:
    """
    Converts a 2-bytes (16 bits) string to a signed integer.

    :param c: string containing bytes to convert
    :param o: offset of bytes to convert in string
    """
    ...

def si16be(c, o=...): # -> Any:
    """
    Converts a 2-bytes (16 bits) string to a signed integer, big endian.

    :param c: string containing bytes to convert
    :param o: offset of bytes to convert in string
    """
    ...

def i32le(c, o=...): # -> Any:
    """
    Converts a 4-bytes (32 bits) string to an unsigned integer.

    :param c: string containing bytes to convert
    :param o: offset of bytes to convert in string
    """
    ...

def si32le(c, o=...): # -> Any:
    """
    Converts a 4-bytes (32 bits) string to a signed integer.

    :param c: string containing bytes to convert
    :param o: offset of bytes to convert in string
    """
    ...

def i16be(c, o=...): # -> Any:
    ...

def i32be(c, o=...): # -> Any:
    ...

def o16le(i): # -> bytes:
    ...

def o32le(i): # -> bytes:
    ...

def o16be(i): # -> bytes:
    ...

def o32be(i): # -> bytes:
    ...

