"""
This type stub file was generated by pyright.
"""

import sys

""" Find compiled module linking to Tcl / Tk libraries
"""
if hasattr(sys, "pypy_find_executable"):
    TKINTER_LIB = ...
else:
    TKINTER_LIB = ...
tk_version = ...
