"""
This type stub file was generated by pyright.
"""

def is_path(f): # -> bool:
    ...

def is_directory(f): # -> bool:
    """Checks if an object is a string, and that it points to a directory."""
    ...

class DeferredError:
    def __init__(self, ex) -> None:
        ...
    
    def __getattr__(self, elt):
        ...
    


