"""
This type stub file was generated by pyright.
"""

from . import FontFile

"""
Parse X Bitmap Distribution Format (BDF)
"""
bdf_slant = ...
bdf_spacing = ...
def bdf_char(f): # -> tuple[Any, int, tuple[tuple[int, int], tuple[int, int, int, int], tuple[int, int, int, int]], Image] | None:
    ...

class BdfFontFile(FontFile.FontFile):
    """Font file plugin for the X11 BDF format."""
    def __init__(self, fp) -> None:
        ...
    


