"""
This type stub file was generated by pyright.
"""

from . import ImageFile

_handler = ...
def register_handler(handler): # -> None:
    """
    Install application-specific BUFR image handler.

    :param handler: Handler object.
    """
    ...

class BufrStubImageFile(ImageFile.StubImageFile):
    format = ...
    format_description = ...


