"""
This type stub file was generated by pyright.
"""

modules = ...
def check_module(feature): # -> bool:
    """
    Checks if a module is available.

    :param feature: The module to check for.
    :returns: ``True`` if available, ``False`` otherwise.
    :raises ValueError: If the module is not defined in this version of Pillow.
    """
    ...

def version_module(feature): # -> Any | None:
    """
    :param feature: The module to check for.
    :returns:
        The loaded version number as a string, or ``None`` if unknown or not available.
    :raises ValueError: If the module is not defined in this version of Pillow.
    """
    ...

def get_supported_modules(): # -> list[str]:
    """
    :returns: A list of all supported modules.
    """
    ...

codecs = ...
def check_codec(feature): # -> bool:
    """
    Checks if a codec is available.

    :param feature: The codec to check for.
    :returns: ``True`` if available, ``False`` otherwise.
    :raises ValueError: If the codec is not defined in this version of Pillow.
    """
    ...

def version_codec(feature): # -> Any | None:
    """
    :param feature: The codec to check for.
    :returns:
        The version number as a string, or ``None`` if not available.
        Checked at compile time for ``jpg``, run-time otherwise.
    :raises ValueError: If the codec is not defined in this version of Pillow.
    """
    ...

def get_supported_codecs(): # -> list[str]:
    """
    :returns: A list of all supported codecs.
    """
    ...

features = ...
def check_feature(feature): # -> Any | None:
    """
    Checks if a feature is available.

    :param feature: The feature to check for.
    :returns: ``True`` if available, ``False`` if unavailable, ``None`` if unknown.
    :raises ValueError: If the feature is not defined in this version of Pillow.
    """
    ...

def version_feature(feature): # -> Any | None:
    """
    :param feature: The feature to check for.
    :returns: The version number as a string, or ``None`` if not available.
    :raises ValueError: If the feature is not defined in this version of Pillow.
    """
    ...

def get_supported_features(): # -> list[str]:
    """
    :returns: A list of all supported features.
    """
    ...

def check(feature): # -> bool | Any | None:
    """
    :param feature: A module, codec, or feature name.
    :returns:
        ``True`` if the module, codec, or feature is available,
        ``False`` or ``None`` otherwise.
    """
    ...

def version(feature): # -> Any | None:
    """
    :param feature:
        The module, codec, or feature to check for.
    :returns:
        The version number as a string, or ``None`` if unknown or not available.
    """
    ...

def get_supported(): # -> list[str]:
    """
    :returns: A list of all supported modules, features, and codecs.
    """
    ...

def pilinfo(out=..., supported_formats=...): # -> None:
    """
    Prints information about this installation of Pillow.
    This function can be called with ``python3 -m PIL``.

    :param out:
        The output stream to print to. Defaults to ``sys.stdout`` if ``None``.
    :param supported_formats:
        If ``True``, a list of all supported image file formats will be printed.
    """
    ...

