"""
This type stub file was generated by pyright.
"""

from . import ImageFile

class FliImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    _close_exclusive_fp_after_loading = ...
    def seek(self, frame): # -> None:
        ...
    
    def tell(self): # -> int:
        ...
    


