"""
This type stub file was generated by pyright.
"""

WIDTH = ...
def puti16(fp, values): # -> None:
    """Write network order (big-endian) 16-bit sequence"""
    ...

class FontFile:
    """Base class for raster font file handlers."""
    bitmap = ...
    def __init__(self) -> None:
        ...
    
    def __getitem__(self, ix):
        ...
    
    def compile(self): # -> Literal[''] | None:
        """Create metrics and bitmap"""
        ...
    
    def save(self, filename): # -> None:
        """Save font"""
        ...
    


