"""
This type stub file was generated by pyright.
"""

from . import ImageFile

MODES = ...
class FpxImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def load(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


