"""
This type stub file was generated by pyright.
"""

from . import ImageFile

class GbrImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def load(self): # -> None:
        ...
    


