"""
This type stub file was generated by pyright.
"""

class GimpPaletteFile:
    """File handler for GIMP's palette format."""
    rawmode = ...
    def __init__(self, fp) -> None:
        ...
    
    def getpalette(self): # -> tuple[list[bytes] | bytes, str]:
        ...
    


