"""
This type stub file was generated by pyright.
"""

"""
Stuff to translate curve segments to palette values (derived from
the corresponding code in GIMP, written by Federico Mena Quintero.
See the GIMP distribution for more information.)
"""
EPSILON = ...
def linear(middle, pos): # -> float:
    ...

def curved(middle, pos):
    ...

def sine(middle, pos): # -> float:
    ...

def sphere_increasing(middle, pos): # -> float:
    ...

def sphere_decreasing(middle, pos): # -> float:
    ...

SEGMENTS = ...
class GradientFile:
    gradient = ...
    def getpalette(self, entries=...): # -> tuple[bytes, Literal['RGBA']]:
        ...
    


class GimpGradientFile(GradientFile):
    """File handler for GIMP's gradient format."""
    def __init__(self, fp) -> None:
        ...
    


