"""
This type stub file was generated by pyright.
"""

qt_versions = ...
def rgb(r, g, b, a=...):
    """(Internal) Turns an RGB color into a Qt compatible color integer."""
    ...

def fromqimage(im):
    """
    :param im: QImage or PIL ImageQt object
    """
    ...

def fromqpixmap(im):
    ...

def align8to32(bytes, width, mode): # -> bytes:
    """
    converts each scanline of data from 8 bit to 32 bit aligned
    """
    ...

if qt_is_installed:
    class ImageQt(QImage):
        def __init__(self, im) -> None:
            """
            An PIL image wrapper for Qt.  This is a subclass of PyQt's QImage
            class.

            :param im: A PIL Image object, or a file name (given either as
                Python string or a PyQt string object).
            """
            ...
        
    
    
def toqimage(im): # -> ImageQt:
    ...

def toqpixmap(im):
    ...

