"""
This type stub file was generated by pyright.
"""

class Stat:
    def __init__(self, image_or_list, mask=...) -> None:
        ...
    
    def __getattr__(self, id): # -> Any:
        """Calculate missing attribute"""
        ...
    


Global = Stat
