"""
This type stub file was generated by pyright.
"""

_modes = ...
class ModeDescriptor:
    """Wrapper for mode strings."""
    def __init__(self, mode, bands, basemode, basetype, typestr) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def getmode(mode):
    """Gets a mode descriptor for the given mode."""
    ...

