"""
This type stub file was generated by pyright.
"""

class Iterator:
    """
    This class implements an iterator object that can be used to loop
    over an image sequence.

    You can use the ``[]`` operator to access elements by index. This operator
    will raise an :py:exc:`IndexError` if you try to access a nonexistent
    frame.

    :param im: An image object.
    """
    def __init__(self, im) -> None:
        ...
    
    def __getitem__(self, ix): # -> Any:
        ...
    
    def __iter__(self): # -> Self:
        ...
    
    def __next__(self): # -> Any:
        ...
    


def all_frames(im, func=...): # -> list[Any]:
    """
    Applies a given function to all frames in an image or a list of images.
    The frames are returned as a list of separate images.

    :param im: An image, or a list of images.
    :param func: The function to apply to all of the image frames.
    :returns: A list of images.
    """
    ...

