"""
This type stub file was generated by pyright.
"""

class _Operand:
    """Wraps an image operand, providing standard operators"""
    def __init__(self, im) -> None:
        ...
    
    def apply(self, op, im1, im2=..., mode=...): # -> _Operand:
        ...
    
    def __bool__(self): # -> bool:
        ...
    
    def __abs__(self): # -> _Operand:
        ...
    
    def __pos__(self): # -> Self:
        ...
    
    def __neg__(self): # -> _Operand:
        ...
    
    def __add__(self, other): # -> _Operand:
        ...
    
    def __radd__(self, other): # -> _Operand:
        ...
    
    def __sub__(self, other): # -> _Operand:
        ...
    
    def __rsub__(self, other): # -> _Operand:
        ...
    
    def __mul__(self, other): # -> _Operand:
        ...
    
    def __rmul__(self, other): # -> _Operand:
        ...
    
    def __truediv__(self, other): # -> _Operand:
        ...
    
    def __rtruediv__(self, other): # -> _Operand:
        ...
    
    def __mod__(self, other): # -> _Operand:
        ...
    
    def __rmod__(self, other): # -> _Operand:
        ...
    
    def __pow__(self, other): # -> _Operand:
        ...
    
    def __rpow__(self, other): # -> _Operand:
        ...
    
    def __invert__(self): # -> _Operand:
        ...
    
    def __and__(self, other): # -> _Operand:
        ...
    
    def __rand__(self, other): # -> _Operand:
        ...
    
    def __or__(self, other): # -> _Operand:
        ...
    
    def __ror__(self, other): # -> _Operand:
        ...
    
    def __xor__(self, other): # -> _Operand:
        ...
    
    def __rxor__(self, other): # -> _Operand:
        ...
    
    def __lshift__(self, other): # -> _Operand:
        ...
    
    def __rshift__(self, other): # -> _Operand:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __le__(self, other) -> bool:
        ...
    
    def __gt__(self, other) -> bool:
        ...
    
    def __ge__(self, other) -> bool:
        ...
    


def imagemath_int(self): # -> _Operand:
    ...

def imagemath_float(self): # -> _Operand:
    ...

def imagemath_equal(self, other):
    ...

def imagemath_notequal(self, other):
    ...

def imagemath_min(self, other):
    ...

def imagemath_max(self, other):
    ...

def imagemath_convert(self, mode): # -> _Operand:
    ...

ops = ...
def eval(expression, _dict=..., **kw): # -> Any:
    """
    Evaluates an image expression.

    :param expression: A string containing a Python-style expression.
    :param options: Values to add to the evaluation context.  You
                    can either use a dictionary, or one or more keyword
                    arguments.
    :return: The evaluated expression. This is usually an image object, but can
             also be an integer, a floating point value, or a pixel tuple,
             depending on the expression.
    """
    ...

