"""
This type stub file was generated by pyright.
"""

from . import ImageFile

COMPRESSION = ...
PAD = ...
def i(c): # -> Any:
    ...

def dump(c): # -> None:
    ...

class IptcImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def getint(self, key): # -> Any:
        ...
    
    def field(self): # -> tuple[None, Literal[0]] | tuple[tuple[Any, Any], Any | Literal[0]]:
        ...
    
    def load(self): # -> None:
        ...
    


def getiptcinfo(im): # -> dict[Any, Any] | None:
    """
    Get IPTC information from TIFF, JPEG, or IPTC file.

    :param im: An image containing IPTC data.
    :returns: A dictionary containing IPTC information, or None if
        no IPTC information block was found.
    """
    class FakeImage:
        ...
    
    

