"""
This type stub file was generated by pyright.
"""

from . import ImageFile

def Skip(self, marker): # -> None:
    ...

def APP(self, marker):
    ...

def COM(self, marker): # -> None:
    ...

def SOF(self, marker): # -> None:
    ...

def DQT(self, marker): # -> None:
    ...

MARKER = ...
class JpegImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def load_read(self, read_bytes): # -> Literal[b"\xff\xd9"]:
        """
        internal: read more image data
        For premature EOF and LOAD_TRUNCATED_IMAGES adds EOI marker
        so libjpeg can finish decoding
        """
        ...
    
    def draft(self, mode, size): # -> tuple[str | Any, tuple[Literal[0], Literal[0], Any | float, Any | float]] | None:
        ...
    
    def load_djpeg(self): # -> None:
        ...
    
    def getxmp(self): # -> dict[Any, Any] | dict[str, str | dict[str, str] | None]:
        """
        Returns a dictionary containing the XMP tags.
        Requires defusedxml to be installed.

        :returns: XMP tags in a dictionary.
        """
        ...
    


RAWMODE = ...
zigzag_index = ...
samplings = ...
def get_sampling(im): # -> int:
    ...

def jpeg_factory(fp=..., filename=...): # -> JpegImageFile:
    ...

