"""
This type stub file was generated by pyright.
"""

from . import TiffImagePlugin

class MicImageFile(TiffImagePlugin.TiffImageFile):
    format = ...
    format_description = ...
    _close_exclusive_fp_after_loading = ...
    def seek(self, frame): # -> None:
        ...
    
    def tell(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


