"""
This type stub file was generated by pyright.
"""

from . import ImageFile

class BitStream:
    def __init__(self, fp) -> None:
        ...
    
    def next(self):
        ...
    
    def peek(self, bits):
        ...
    
    def skip(self, bits): # -> None:
        ...
    
    def read(self, bits):
        ...
    


class MpegImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...


