"""
This type stub file was generated by pyright.
"""

from . import JpegImagePlugin

class MpoImageFile(JpegImagePlugin.JpegImageFile):
    format = ...
    format_description = ...
    _close_exclusive_fp_after_loading = ...
    def load_seek(self, pos): # -> None:
        ...
    
    def seek(self, frame): # -> None:
        ...
    
    def tell(self): # -> int:
        ...
    
    @staticmethod
    def adopt(jpeg_instance, mpheader=...):
        """
        Transform the instance of JpegImageFile into
        an instance of MpoImageFile.
        After the call, the JpegImageFile is extended
        to be an MpoImageFile.

        This is essentially useful when opening a JPEG
        file that reveals itself as an MPO, to avoid
        double call to _open.
        """
        ...
    


