"""
This type stub file was generated by pyright.
"""

class PaletteFile:
    """File handler for Teragon-style palette files."""
    rawmode = ...
    def __init__(self, fp) -> None:
        ...
    
    def getpalette(self): # -> tuple[list[tuple[int, int, int]] | bytes, str]:
        ...
    


