"""
This type stub file was generated by pyright.
"""

from . import ImageFile

class PcdImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def load_end(self): # -> None:
        ...
    


