"""
This type stub file was generated by pyright.
"""

from . import ImageFile

b_whitespace = ...
MODES = ...
class PpmImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...


class PpmPlainDecoder(ImageFile.PyDecoder):
    _pulls_fd = ...
    def decode(self, buffer): # -> tuple[Literal[-1], Literal[0]]:
        ...
    


class PpmDecoder(ImageFile.PyDecoder):
    _pulls_fd = ...
    def decode(self, buffer): # -> tuple[Literal[-1], Literal[0]]:
        ...
    


