"""
This type stub file was generated by pyright.
"""

from . import ImageFile

class QoiImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...


class QoiDecoder(ImageFile.PyDecoder):
    _pulls_fd = ...
    def decode(self, buffer): # -> tuple[Literal[-1], Literal[0]]:
        ...
    


