"""
This type stub file was generated by pyright.
"""

from . import ImageFile

MODES = ...
class SgiImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...


class SGI16Decoder(ImageFile.PyDecoder):
    _pulls_fd = ...
    def decode(self, buffer): # -> tuple[Literal[-1], Literal[0]]:
        ...
    


