"""
This type stub file was generated by pyright.
"""

from . import ContainerIO

class TarIO(ContainerIO.ContainerIO):
    """A file object that provides read access to a given member of a TAR file."""
    def __init__(self, tarfile, file) -> None:
        """
        Create file object.

        :param tarfile: Name of TAR file.
        :param file: Name of member file.
        """
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


