"""
This type stub file was generated by pyright.
"""

from . import Image, ImageFile

_handler = ...
def register_handler(handler): # -> None:
    """
    Install application-specific WMF image handler.

    :param handler: Handler object.
    """
    ...

if hasattr(Image.core, "drawwmf"):
    class WmfHandler:
        def open(self, im): # -> None:
            ...
        
        def load(self, im): # -> Image:
            ...
        
    
    
class WmfStubImageFile(ImageFile.StubImageFile):
    format = ...
    format_description = ...
    def load(self, dpi=...):
        ...
    


