"""
This type stub file was generated by pyright.
"""

from . import ImageFile

xpm_head = ...
class XpmImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def load_read(self, bytes): # -> bytes:
        ...
    


