"""
This type stub file was generated by pyright.
"""

from boto3.docs.base import NestedDocumenter

class WaiterResourceDocumenter(NestedDocumenter):
    def __init__(self, resource, service_waiter_model, root_docs_path) -> None:
        ...
    
    def document_resource_waiters(self, section): # -> None:
        ...
    


def document_resource_waiter(section, resource_name, event_emitter, service_model, resource_waiter_model, service_waiter_model, include_signature=...): # -> None:
    ...

